spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

workapi:
  serverAddress: https://workapi.neo-works.co.kr

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


